# Generated by Django 3.0.4 on 2020-04-21 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200402_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'required': 'Please enter your first name'}, help_text='имя', max_length=32, validators=[django.core.validators.RegexValidator('[A-Za-z]{1,32}')], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(error_messages={'required': 'Please enter your last name'}, help_text='фамилия', max_length=32, validators=[django.core.validators.RegexValidator('[A-Za-z]{1,32}')], verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_text',
            field=models.CharField(blank=True, max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(help_text='отчество', max_length=32, null=True, validators=[django.core.validators.RegexValidator('[A-Za-z]{1,32}')], verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='логин', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('[A-Za-z]{1,32}')], verbose_name='Username'),
        ),
    ]
